development:
  adapter: mysql
  database: news_development
  hostname: localhost
  username: root
  socket: /opt/local/var/run/mysql5/mysqld.sock

test:
  adapter: mysql
  database: news_test
  hostname: localhost
  username: root
  socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql
  database: news_production
  hostname: localhost
  username: root
  socket: /opt/local/var/run/mysql5/mysqld.sock
